/******************************************************************************
 * This file is auto-generated by Vaadin.
 * If you want to customize the entry point, you can copy this file or create
 * your own `index.tsx` in your frontend directory.
 * By default, the `index.tsx` file should be in `./frontend/` folder.
 *
 * NOTE:
 *     - You need to restart the dev-server after adding the new `index.tsx` file.
 *       After that, all modifications to `index.tsx` are recompiled automatically.
 *     - `index.js` is also supported if you don't want to use TypeScript.
 ******************************************************************************/

import { createElement } from 'react';
import { createRoot } from 'react-dom/client';
import { RouterProvider } from 'react-router';
import { router } from 'Frontend/generated/routes.js';
import { AuthProvider } from './security/auth';
// Asegúrate de que la ruta a tu Carrito sea correcta (quizás está en views)
import { CarritoProvider } from './views/_CarritoContext'; 

function App() {
    return (
        // AQUÍ VIVEN LOS PROVIDERS GLOBALES (Una sola vez para toda la app)
        <AuthProvider>
            <CarritoProvider>
                <RouterProvider router={router} />
            </CarritoProvider>
        </AuthProvider>
    );
}

const outlet = document.getElementById('outlet')!;
let root = (outlet as any)._root ?? createRoot(outlet);
(outlet as any)._root = root;
root.render(createElement(App));